name: Docker Image CI

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: quay.io/${{ secrets.REPOSITORY_USERNAME }}/video-server:${{ github.sha }}

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checking the code out
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.REPOSITORY_USERNAME }}
        password: ${{ secrets.REPOSITORY_PASSWORD }}

    # - name: Build and push docker image
    #   uses: docker/build-push-action@v3
    #   with:
    #     context: .
    #     push: true
    #     tags: ${{ env.IMAGE_TAG }}
    #     platforms: linux/amd64,linux/arm64
    
    - name: Print image tags
      run: |
        echo "${{ env.IMAGE_TAG }}"

    - name: Checking out the charts code
      uses: actions/checkout@v3
      with:
        repository: dunefro/sample-charts
    
    - name: Changing image tag in helm charts
      uses: mikefarah/yq@v4
      with:
        cmd: yq -i '.image.tag = "${{ github.sha }}"' ./charts/video-server/values.yaml
    
    - name: Pushing updated helm charts
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: "."
        destination-github-username: "dunefro"
        destination-repository-name: "sample-charts"
        user-email: dunefro@gmail.com
        target-branch: "image-update"
        commit-message: "[CI] Update values.yaml"
        create-target-branch-if-needed: true
