name: Docker Image CI

on:
  push:
    branches:
      - main
      - release

env:
  IMAGE_TAG: quay.io/${{ secrets.REPOSITORY_USERNAME }}/video-server:${{ github.ref_name }}

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checking the code out
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.REPOSITORY_USERNAME }}
        password: ${{ secrets.REPOSITORY_PASSWORD }}

    - name: Build and push docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_TAG }}
        platforms: linux/amd64,linux/arm64
    
    - name: Print image tags
      run: |
        echo "${{ env.IMAGE_TAG }}"